apiVersion: batch/v1
kind: Job
metadata:
  name: url-worker
spec:
  parallelism: 2
  template:
    metadata:
      name: url-worker
    spec:
      containers:
        - name: url-worker-container
          image: naboagye1/audio-notion-url-worker:latest
      restartPolicy: OnFailure
